// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NesivosHakodesh.Core.DB;

namespace NesivosHakodesh.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210421190024_Roles4")]
    partial class Roles4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NesivosHakodesh.Models.AssignmentResult", b =>
                {
                    b.Property<int>("AssignmentResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("MaamarID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProjectAssignmentID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentResultID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("MaamarID");

                    b.HasIndex("ProjectAssignmentID");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("AssignmentResults");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Maamar", b =>
                {
                    b.Property<int>("MaamarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccuracyDescriptin")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("AccuracyRate")
                        .HasColumnType("int");

                    b.Property<string>("AudioFileName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("BechatzrPrinted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BechatzrPrintedWeek")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LocationDetails")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Parsha")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("PdfFileName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SourceID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int?>("TopicID")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("WeeklyIndex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Year")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("MaamarID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("Date");

                    b.HasIndex("Parsha");

                    b.HasIndex("SourceID");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.HasIndex("TopicID");

                    b.HasIndex("Type");

                    b.HasIndex("UpdatedUserId");

                    b.HasIndex("Year");

                    b.ToTable("Maamarim");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.MaamarParagraph", b =>
                {
                    b.Property<int>("MaamarParagraphID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("MaamarID")
                        .HasColumnType("int");

                    b.Property<int>("ParagraphType")
                        .HasColumnType("int");

                    b.Property<string>("Sort")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("MaamarParagraphID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("MaamarID");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("MaamarimParagraphs");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.MaamarTopic", b =>
                {
                    b.Property<int>("MaamarTopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("MaamarID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TopicID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("MaamarTopicID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("MaamarID");

                    b.HasIndex("TopicID");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("MaamarTopic");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.MaamarTorahLink", b =>
                {
                    b.Property<int>("MaamarTorahLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaamarID")
                        .HasColumnType("int");

                    b.Property<int?>("TorahID")
                        .HasColumnType("int");

                    b.Property<int?>("TorahParagraphID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("MaamarTorahLinkID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("MaamarID");

                    b.HasIndex("TorahID");

                    b.HasIndex("TorahParagraphID");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("MaamarTorahLinks");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.ProjectAssignment", b =>
                {
                    b.Property<int>("ProjectAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProjectUserID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectAssignmentID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("ProjectUserID");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("ProjectAssignments");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.ProjectChapter", b =>
                {
                    b.Property<int>("ProjectChapterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ParentChapterProjectChapterID")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectChapterID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("ParentChapterProjectChapterID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("ProjectChapters");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.ProjectUser", b =>
                {
                    b.Property<int>("ProjectUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectUserID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UpdatedUserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "1434ab56-060f-44d2-9d75-525624ae13e8",
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "76c7e481-4790-4c14-849c-49afb41d0b32",
                            Name = "TOPICS_VIEW"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "690051c3-bef6-40b4-aecc-ae26c6b037bc",
                            Name = "TOPICS_EDIT"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "b77e7050-644b-4bf3-b34f-ed9b66519f54",
                            Name = "SOURCES_VIEW"
                        },
                        new
                        {
                            Id = 5,
                            ConcurrencyStamp = "755d5c21-cafa-4fb0-aaa5-ad8f3591ec63",
                            Name = "SOURCES_EDIT"
                        },
                        new
                        {
                            Id = 6,
                            ConcurrencyStamp = "14501589-aca2-40b6-8347-f0c40409344a",
                            Name = "SOURCES_PRS_VIEW"
                        },
                        new
                        {
                            Id = 7,
                            ConcurrencyStamp = "0d48623a-fdbf-4865-a379-310aadf648e6",
                            Name = "SOURCES_PRS_EDIT"
                        },
                        new
                        {
                            Id = 8,
                            ConcurrencyStamp = "44b3b668-8035-4194-881d-d32c7eb30e1f",
                            Name = "TORHAS_VIEW"
                        },
                        new
                        {
                            Id = 9,
                            ConcurrencyStamp = "bf49ea85-9df1-46e1-8301-c9857631a60e",
                            Name = "TORHAS_EDIT"
                        },
                        new
                        {
                            Id = 10,
                            ConcurrencyStamp = "871c9145-f2fe-4854-8de1-062d4710269f",
                            Name = "MAAMARIM_0_VIEW"
                        },
                        new
                        {
                            Id = 11,
                            ConcurrencyStamp = "73001f2d-328f-42e0-822c-316f3b882db3",
                            Name = "MAAMARIM_0_EDIT"
                        },
                        new
                        {
                            Id = 12,
                            ConcurrencyStamp = "2bb0f23b-1499-4426-8002-8bad2ea4dee2",
                            Name = "MAAMARIM_0_PRINT"
                        },
                        new
                        {
                            Id = 13,
                            ConcurrencyStamp = "490f5777-3f47-4101-b392-94258a73c397",
                            Name = "MAAMARIM_0_DOWNLOAD"
                        },
                        new
                        {
                            Id = 14,
                            ConcurrencyStamp = "c4ef2569-ca24-4f4e-ba87-9a7500a23451",
                            Name = "MAAMARIM_1_VIEW"
                        },
                        new
                        {
                            Id = 15,
                            ConcurrencyStamp = "c5d233b2-c3d9-484e-b278-cc2477344c1d",
                            Name = "MAAMARIM_1_EDIT"
                        },
                        new
                        {
                            Id = 16,
                            ConcurrencyStamp = "dbd10946-8568-48e3-987c-d311fb111c32",
                            Name = "MAAMARIM_1_PRINT"
                        },
                        new
                        {
                            Id = 17,
                            ConcurrencyStamp = "58915745-02d9-48f6-a775-dc79f96bd90b",
                            Name = "MAAMARIM_1_DOWNLOAD"
                        },
                        new
                        {
                            Id = 18,
                            ConcurrencyStamp = "187a7d42-67dd-4944-ab7d-c90929f22c26",
                            Name = "MAAMARIM_2_VIEW"
                        },
                        new
                        {
                            Id = 19,
                            ConcurrencyStamp = "29f971f5-a5de-438c-9916-eff9f45a6609",
                            Name = "MAAMARIM_2_EDIT"
                        },
                        new
                        {
                            Id = 20,
                            ConcurrencyStamp = "96b9d9f3-d3a1-47e9-ac81-294185e7d71f",
                            Name = "MAAMARIM_2_PRINT"
                        },
                        new
                        {
                            Id = 21,
                            ConcurrencyStamp = "71fc65ff-67e6-418e-9494-6cad02b71b16",
                            Name = "MAAMARIM_2_DOWNLOAD"
                        },
                        new
                        {
                            Id = 22,
                            ConcurrencyStamp = "616169e8-c1e7-4dcb-8ff5-4de49c0b6238",
                            Name = "MAAMARIM_3_VIEW"
                        },
                        new
                        {
                            Id = 23,
                            ConcurrencyStamp = "448b7f87-c5d9-4194-be55-e59996d6a683",
                            Name = "MAAMARIM_3_EDIT"
                        },
                        new
                        {
                            Id = 24,
                            ConcurrencyStamp = "7a8cb5f0-26f6-49a4-9998-588f43354470",
                            Name = "MAAMARIM_3_PRINT"
                        },
                        new
                        {
                            Id = 25,
                            ConcurrencyStamp = "dc6679bd-3a62-407b-add3-151de1555ade",
                            Name = "MAAMARIM_3_DOWNLOAD"
                        },
                        new
                        {
                            Id = 26,
                            ConcurrencyStamp = "e5858795-e5da-440c-9bdc-51174bcacfd1",
                            Name = "MAAMARIM_VIEW"
                        });
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Sefer", b =>
                {
                    b.Property<int>("SeferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FileUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("OutlineJson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("SeferID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("Name");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("Sefurim");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Source", b =>
                {
                    b.Property<int>("SourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssingedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SourceDetails")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("SourceID");

                    b.HasIndex("AssingedUserId");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Topic", b =>
                {
                    b.Property<int>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ParentTopicTopicID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("TopicID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("ParentTopicTopicID");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Torah", b =>
                {
                    b.Property<int>("TorahID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("AnnHeight")
                        .HasColumnType("double");

                    b.Property<int?>("AnnPageNumber")
                        .HasColumnType("int");

                    b.Property<double?>("AnnWidth")
                        .HasColumnType("double");

                    b.Property<double?>("AnnX")
                        .HasColumnType("double");

                    b.Property<double?>("AnnY")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Index")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MaarahMakoim")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Parsha")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int?>("SeferID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("TorahID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("Parsha");

                    b.HasIndex("SeferID");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("Torahs");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.TorahParagraph", b =>
                {
                    b.Property<int>("TorahParagraphID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SortIndex")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("TorahID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedUserId")
                        .HasColumnType("int");

                    b.HasKey("TorahParagraphID");

                    b.HasIndex("CreatedUserId");

                    b.HasIndex("TorahID");

                    b.HasIndex("UpdatedUserId");

                    b.ToTable("TorahParagraphs");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Cell")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.AssignmentResult", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Maamar", "Maamar")
                        .WithMany()
                        .HasForeignKey("MaamarID");

                    b.HasOne("NesivosHakodesh.Models.ProjectAssignment", "ProjectAssignment")
                        .WithMany("AssignmentResults")
                        .HasForeignKey("ProjectAssignmentID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Maamar", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceID");

                    b.HasOne("NesivosHakodesh.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.MaamarParagraph", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Maamar", null)
                        .WithMany("MaamarParagraphs")
                        .HasForeignKey("MaamarID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.MaamarTopic", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Maamar", "Maamar")
                        .WithMany("SubTopics")
                        .HasForeignKey("MaamarID");

                    b.HasOne("NesivosHakodesh.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.MaamarTorahLink", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Maamar", "Maamar")
                        .WithMany("TorahLinks")
                        .HasForeignKey("MaamarID");

                    b.HasOne("NesivosHakodesh.Models.Torah", "Torah")
                        .WithMany("MaamarLinks")
                        .HasForeignKey("TorahID");

                    b.HasOne("NesivosHakodesh.Models.TorahParagraph", "TorahParagraph")
                        .WithMany()
                        .HasForeignKey("TorahParagraphID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Project", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.User", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.ProjectAssignment", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.ProjectUser", "ProjectUser")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("ProjectUserID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.ProjectChapter", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.ProjectChapter", "ParentChapter")
                        .WithMany()
                        .HasForeignKey("ParentChapterProjectChapterID");

                    b.HasOne("NesivosHakodesh.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.ProjectUser", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");

                    b.HasOne("NesivosHakodesh.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Sefer", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Source", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "AssingedUser")
                        .WithMany()
                        .HasForeignKey("AssingedUserId");

                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Topic", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Topic", "ParentTopic")
                        .WithMany()
                        .HasForeignKey("ParentTopicTopicID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.Torah", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Sefer", "Sefer")
                        .WithMany("Torahs")
                        .HasForeignKey("SeferID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.TorahParagraph", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId");

                    b.HasOne("NesivosHakodesh.Models.Torah", null)
                        .WithMany("TorahParagraphs")
                        .HasForeignKey("TorahID");

                    b.HasOne("NesivosHakodesh.Models.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedUserId");
                });

            modelBuilder.Entity("NesivosHakodesh.Models.UserRole", b =>
                {
                    b.HasOne("NesivosHakodesh.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NesivosHakodesh.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
